"""Adding new table expense

Revision ID: 34bca1f7461f
Revises: 5a3852d82751
Create Date: 2024-07-04 07:34:20.354063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34bca1f7461f'
down_revision: Union[str, None] = '5a3852d82751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('paid_by_id', sa.Integer(), nullable=True),
    sa.Column('paid_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_amount'), 'expenses', ['amount'], unique=False)
    op.create_index(op.f('ix_expenses_description'), 'expenses', ['description'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_description'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_amount'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
